### ISSUE TITLE
Incompatibility with channels-rabbitmq

### ISSUE THREAD

**Issue by rakyi** [datadvance/DjangoChannelsGraphqlWs#11] opened 2019-04-05 15:16 UTC
I got errors when trying to use django-channels-graphql-ws together with channels-rabbitmq, see https://github.com/CJWorkbench/channels_rabbitmq/issues/3.

I don't understand the intricacies of the underlying problem, but I think you might at least appreciate the analysis provided by channels-rabbitmq's maintainer in the linked issue.

**Comment by prokher** [comment] 2019-04-19 14:34
The problem is that "channels-rabbitmq" stores server-side info attached to the connection. I am not the person to blame, but I am not sure if such behavior complies to the ASGI specification. Anyway, we've made some changes to improve, so now we work with Channels groups from a single eventloop within a single thread. So the issue seems to be fixed in 0.1.18.

Please check & reopen the issue if the problem stays.

**Closed by prokher** 2019-04-19 14:34 UTC
