### ISSUE TITLE
Error "can't serialize <model instance>" when using channels_redis as channel layer

### ISSUE THREAD

**Issue by xaralis** [datadvance/DjangoChannelsGraphqlWs#5] opened 2018-07-11 10:54 UTC
When having following subscription code (`MessageModel` is a Django model class):

```python
class Message(DjangoObjectType):
    class Meta:
        model = MessageModel

class MessageAddedSubscription(channels_graphql_ws.Subscription):
    Output = Message

    @staticmethod
    def publish(payload, info):
        return payload
```

and calling broadcast elsewhere like this:

```python
new_message = MessageModel.objects.create(text='some text')
MessageAddedSubscription.broadcast(payload=new_message)
```

... application crashes because it's unable to serialize the model instance to redis-backed channel layer:

```
An error occurred while resolving field Mutations.messageAdd
Traceback (most recent call last):
  File "/Users/xaralis/.venvs/obs/lib/python3.6/site-packages/graphql/execution/executor.py", line 311, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/Users/xaralis/.venvs/obs/lib/python3.6/site-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
  File "/Users/xaralis/.venvs/obs/lib/python3.6/site-packages/graphene_django/debug/middleware.py", line 56, in resolve
    promise = next(root, info, **args)
  File "/Users/xaralis/.venvs/obs/lib/python3.6/site-packages/graphql/execution/middleware.py", line 57, in make_it_promise
    return Promise.resolve(next(*a, **b))
  File "/Users/xaralis/Workspace/obs/obs-server/obs/schema.py", line 30, in mutate
    MessageAddedSubscription.broadcast(payload=new_message)
  File "/Users/xaralis/.venvs/obs/lib/python3.6/site-packages/channels_graphql_ws/graphql_ws.py", line 182, in broadcast
    'payload': payload})
  File "/Users/xaralis/.venvs/obs/lib/python3.6/site-packages/asgiref/sync.py", line 64, in __call__
    return call_result.result()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/xaralis/.venvs/obs/lib/python3.6/site-packages/asgiref/sync.py", line 78, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/Users/xaralis/.venvs/obs/lib/python3.6/site-packages/channels_redis/core.py", line 317, in group_send
    self._map_channel_to_connection(channel_names, message)
  File "/Users/xaralis/.venvs/obs/lib/python3.6/site-packages/channels_redis/core.py", line 368, in _map_channel_to_connection
    channel_to_message[channel] = self.serialize(message)
  File "/Users/xaralis/.venvs/obs/lib/python3.6/site-packages/channels_redis/core.py", line 386, in serialize
    value = msgpack.packb(message, use_bin_type=True)
  File "/Users/xaralis/.venvs/obs/lib/python3.6/site-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 284, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 290, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 287, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 234, in msgpack._packer.Packer._pack
  File "msgpack/_packer.pyx", line 281, in msgpack._packer.Packer._pack
TypeError: can't serialize <Message: Message object (39)>
Traceback (most recent call last):
  File "/Users/xaralis/.venvs/obs/lib/python3.6/site-packages/graphql/execution/executor.py", line 330, in complete_value_catching_error
    exe_context, return_type, field_asts, info, result)
  File "/Users/xaralis/.venvs/obs/lib/python3.6/site-packages/graphql/execution/executor.py", line 383, in complete_value
    raise GraphQLLocatedError(field_asts, original_error=result)
graphql.error.located_error.GraphQLLocatedError: can't serialize <Message: Message object (39)>
```

What is the recommended way to handle Django model instances? Thanks

**Comment by prokher** [comment] 2018-07-17 19:41
When I faced this problem for the first time I went to the decision to use Django serializers for this. You can read about it in [Serializing Django objects](https://docs.djangoproject.com/en/2.0/topics/serialization/#serializing-django-objects) I am not completely sure it is proper design decision, but it works quite smooth in our cases.

Here is the pair of utility methods I wrote for this:
```python

import django.core.serializers

def to_str(model, format='json'):
    """Serialize the model to the string.

    See: https://docs.djangoproject.com/en/dev/topics/serialization/.

    Args:
        model: Django model (subclass of `django.db.models.Model`).
        format: The serialization format, `json` by default.
    Returns:
        String with serialized model.
    """
    return django.core.serializers.serialize(format, [model])


def from_str(model_str, format='json'):
    """Deserialize the model from the string.

    See: https://docs.djangoproject.com/en/dev/topics/serialization/.

    Args:
        model_str: String with serialized model.
        format: The serialization format, `json` by default.
    Returns:
        Unsaved Django model object.
    """
    # Get the first and the only instance of `DeserializedObject`.
    result = next(django.core.serializers.deserialize(format, model_str))
    # Extract the Django model.
    result = result.object

    return result
```

**Comment by prokher** [comment] 2018-07-18 17:48
We could add these two utility function somewhere to the package. @xaralis What do you think?

**Comment by xaralis** [comment] 2018-07-20 08:50
@prokher How exactly are you using these transofmrations? Do you set `Output` to a single string or you can keep it as a model instance and hook up the serializer somewhere in the middle?

**Comment by prokher** [comment] 2018-07-23 11:22
@xaralis First you need to deliver the model from the `broadcast` invocation to the `publish` method. It can be done with help of the functions above like this:
```python
class Message(DjangoObjectType):
    class Meta:
        model = MessageModel

class MessageAddedSubscription(channels_graphql_ws.Subscription):
    Output = Message

    @staticmethod
    def publish(payload, info):
        deserialized_message_model = from_str(payload)
        return MessageAddedSubscription.Output(deserialized_message_model)

# Trigger the subscription.
MessageAddedSubscription.broadcast(payload=to_str(message_model))
```

I am not sure that `DjangoObjectType` works correctly with deserialized models, please let me know if this helps.

**Comment by xaralis** [comment] 2018-07-24 07:30
@prokher Thanks for the example. I'm wondering though, if this cannot be baked in to `DjangoChannelsGraphqlWs` directly instead of requiring user to do the work. For me, it feels like something what library user shouldn't have to solve (sooner or later, everyone bumps into this).

And it seems it shouldn't be difficult to do. Just detect if Django model is being dealt with and if thats the case, send it down serialized through the channel. When calling publish, detect if this was a model once again and if it was, deserialize it.

**Comment by prokher** [comment] 2018-07-24 07:48
@xaralis This is a tricky question. I could implement such heuristic, but what if `payload` is some object which attribute is a Django model? What is `payload` is a dictionary which has Django model as on of the values? Would it be correct to analyze the structure of the `payload` that deep?

On the other hand, the `payload` is serialized by the Channels (which uses MessagePack I think), so it anyway analyzes the `payload` structure. Well, I will take a look if it is possible to provide an automatic serializer for the Django models.

**Comment by xaralis** [comment] 2018-07-24 08:07
@prokher I would only implement it for case when Django model instance equals to payload. Not in case it's nested somewhere down the road. For these more complicated cases, mention the need to serialize/deserialize payload in the README should suffice.

**Comment by prokher** [comment] 2018-08-06 15:05
@xaralis I believe the issue is solved in b5a1b56c70cbc9b632bb35b67322107ff204bc65 and available in 0.1.10. Closing this issue. Feel free to reopen (or create a new one) if something goes wrong.

**Closed by prokher** 2018-08-06 15:05 UTC
Labels: question

**Comment by xaralis** [comment] 2018-08-07 08:54
@prokher You're awesome!

**Comment by bewestphal** [comment] 2020-05-24 01:40
I wanted to make the `message` object the same as one from a query so it's easier to manipulate in the client.

This had me stuck for a while, so leaving this for anyone that comes here from google.

Testing on
`django==3.0.6`
`graphene-django==2.10.1`
`django-channels-graphql-ws==0.5.0`

```
class ChatSubscription(channels_graphql_ws.Subscription):
    """Subscription triggers on a new chat message."""

    message = graphene.Field(Message)
  
   # ....the rest of your subscription class

   def publish(message: MessageModel, info: ResolveInfo, **arguments):
       return ChatSubscription(message=message)

   @classmethod
    def new_message(cls, message: MessageModel):
        cls.broadcast(group=message.chat_id, payload=message)
```
