### ISSUE TITLE
GraphQLLocatedError in scope_as_context when running any query

### ISSUE THREAD

**Issue by morinx** [datadvance/DjangoChannelsGraphqlWs#33] opened 2019-11-16 17:43 UTC
I'm getting the following error when running any query

```json
Traceback (most recent call last):
  File "/Users/x/.pyenv/versions/nexus37/lib/python3.7/site-packages/graphql/execution/executor.py", line 450, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/Users/x/.pyenv/versions/nexus37/lib/python3.7/site-packages/graphql/execution/executors/asyncio.py", line 69, in execute
    result = fn(*args, **kwargs)
  File "/Users/x/.pyenv/versions/nexus37/lib/python3.7/site-packages/channels_graphql_ws/graphql_ws_consumer.py", line 583, in register_middleware
    return next_middleware(root, info, *args, **kwds)
  File "/Users/x/Desktop/github/nexus/nexus/graphql/decorators.py", line 22, in func_wrapper
    oauth_valid, r = OAuthLibCore.verify_request(request, scopes=[])
  File "/Users/x/.pyenv/versions/nexus37/lib/python3.7/site-packages/oauth2_provider/oauth2_backends.py", line 165, in verify_request
    uri, http_method, body, headers = self._extract_params(request)
  File "/Users/x/.pyenv/versions/nexus37/lib/python3.7/site-packages/oauth2_provider/oauth2_backends.py", line 50, in _extract_params
    uri = self._get_escaped_full_path(request)
  File "/Users/x/.pyenv/versions/nexus37/lib/python3.7/site-packages/oauth2_provider/oauth2_backends.py", line 26, in _get_escaped_full_path
    parsed = list(urlparse(request.get_full_path()))
  File "/Users/x/.pyenv/versions/nexus37/lib/python3.7/site-packages/channels_graphql_ws/scope_as_context.py", line 44, in __getattr__
    raise AttributeError() from ex
graphql.error.located_error.GraphQLLocatedError
```

Not sure if related but I tried adding [this middleware ](https://gist.github.com/rluts/22e05ed8f53f97bdd02eafdf38f3d60a#gistcomment-3009758) and add `user` to scope as suggested [here](https://github.com/datadvance/DjangoChannelsGraphqlWs/issues/23#issuecomment-524325390)

Any suggestion as to what is causing this?

**Comment by prokher** [comment] 2020-04-04 23:44
I don't even have a clue. Can you please provide complete example to reproduce an issues? For instance you can take [this example](https://github.com/datadvance/DjangoChannelsGraphqlWs#example) and make it fail by adding the middleware you mentioned. Once we can reproduce this we will take a look.

**Comment by prokher** [comment] 2020-07-25 16:58
Closing this, since I did not received any feedback from @morinx and cannot neither reproduce nor understand what is happening here.

**Comment by prokher** [comment] 2020-07-25 16:58
Reopen if there is new info.

**Closed by prokher** 2020-07-25 16:58 UTC
