### ISSUE TITLE
pip install django-channels-graphql-ws doesn't work

### ISSUE THREAD

**Issue by apratimankur** [datadvance/DjangoChannelsGraphqlWs#25] opened 2019-09-16 18:18 UTC
Installation method mentioned in the readme doesn't work - 
`pip install django-channels-graphql-ws `

Had to install via the wheel --> 
`pip3 install https://files.pythonhosted.org/packages/94/3b/30e63622609d384daa4e1293536994a8b6738715da56793d27e98af48791/django_channels_graphql_ws-0.4.2-py3-none-any.whl`

**Comment by prokher** [comment] 2019-09-17 10:44
Dear @apratimankur , I tried to reproduce the issue you have, but without any success. To be on the safe side I took a clean official Docker image with Python 3.7.4 and installed DjangoChanngelsGraphqlWs with pip without any difficulties. Here is the full log:

```bash
>>> docker run -it --rm python bash
Unable to find image 'python:latest' locally
latest: Pulling from library/python
4a56a430b2ba: Pull complete
4b5cacb629f5: Pull complete
14408c8d4f9a: Pull complete
ea67eaa7dd42: Pull complete
4d134ac3fe4b: Pull complete
4c55f6f5d7f0: Pull complete
6ae475e50652: Pull complete
6f4152644229: Pull complete
6933d3d46042: Pull complete
Digest: sha256:0f0e991a97426db345ca7ec59fa911c8ed27ced27c88ae9966b452bcc6438c2f
Status: Downloaded newer image for python:latest
root@294381deb51f:/# pip install django-channels-graphql-ws
Collecting django-channels-graphql-ws
  Downloading https://files.pythonhosted.org/packages/94/3b/30e63622609d384daa4e1293536994a8b6738715da56793d27e98af48791/django_channels_graphql_ws-0.4.2-py3-none-any.whl
Collecting graphql-core<3.0,>=2.2 (from django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/6a/11/bc4a7eb440124271289d93e4d208bd07d94196038fabbe2a52435a07d3d3/graphql_core-2.2.1-py2.py3-none-any.whl (250kB)
     |████████████████████████████████| 256kB 1.9MB/s
Collecting asgiref<4.0,>=3.2 (from django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/d0/39/42344b1060cfb5542eecef3ce6dda3d2d5a89a660716ed5980635985f2a7/asgiref-3.2.2-py2.py3-none-any.whl
Collecting channels<3.0,>=2.2 (from django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/80/44/8344737fcd2b103b67793d87a790a6c2bdf9a468ea98181f0c87b0d603e7/channels-2.2.0-py2.py3-none-any.whl
Collecting msgpack<0.7.0,>=0.6.1 (from django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/a8/7b/630049fc4af9e68a625738612edc264ce7cb586c5001a2d4d2209a4f61c1/msgpack-0.6.1-cp37-cp37m-manylinux1_x86_64.whl (245kB)
     |████████████████████████████████| 245kB 15.5MB/s
Collecting django<3.0,>=2.2 (from django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/94/9f/a56f7893b1280e5019482260e246ab944d54a9a633a01ed04683d9ce5078/Django-2.2.5-py3-none-any.whl (7.5MB)
     |████████████████████████████████| 7.5MB 9.6MB/s
Collecting aiohttp<4.0,>=3.5 (from django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/5e/86/f505d447c97cf57a0224c7e0e3a79b73b8cc3f0eb6eeed856e7fa48f8f64/aiohttp-3.6.0-cp37-cp37m-manylinux1_x86_64.whl (1.2MB)
     |████████████████████████████████| 1.2MB 10.1MB/s
Collecting graphene<3.0,>=2.1 (from django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/05/97/45e743b372f65a619f8d1eb2897efb74fb1b0ffddc731ad37e0aa187ec5c/graphene-2.1.8-py2.py3-none-any.whl (107kB)
     |████████████████████████████████| 112kB 19.0MB/s
Collecting six>=1.10.0 (from graphql-core<3.0,>=2.2->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting promise>=2.1 (from graphql-core<3.0,>=2.2->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/5a/81/221d09d90176fd90aed4b530e31b8fedf207385767c06d1d46c550c5e418/promise-2.2.1.tar.gz
Collecting rx<3,>=1.6 (from graphql-core<3.0,>=2.2->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/33/0f/5ef4ac78e2a538cc1b054eb86285fe0bf7a5dbaeaac2c584757c300515e2/Rx-1.6.1-py2.py3-none-any.whl (179kB)
     |████████████████████████████████| 184kB 11.6MB/s
Collecting daphne~=2.3 (from channels<3.0,>=2.2->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/43/2e/9b2498d30d7397a27aae5c67f194a9a002be406bdb5a1cb9699de9bb1878/daphne-2.3.0-py2.py3-none-any.whl
Collecting sqlparse (from django<3.0,>=2.2->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/ef/53/900f7d2a54557c6a37886585a91336520e5539e3ae2423ff1102daf4f3a7/sqlparse-0.3.0-py2.py3-none-any.whl
Collecting pytz (from django<3.0,>=2.2->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/87/76/46d697698a143e05f77bec5a526bf4e56a0be61d63425b68f4ba553b51f2/pytz-2019.2-py2.py3-none-any.whl (508kB)
     |████████████████████████████████| 512kB 14.4MB/s
Collecting async-timeout<4.0,>=3.0 (from aiohttp<4.0,>=3.5->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl
Collecting attrs>=17.3.0 (from aiohttp<4.0,>=3.5->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting yarl<2.0,>=1.0 (from aiohttp<4.0,>=3.5->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/fb/84/6d82f6be218c50b547aa29d0315e430cf8a23c52064c92d0a8377d7b7357/yarl-1.3.0.tar.gz (159kB)
     |████████████████████████████████| 163kB 12.2MB/s
Collecting chardet<4.0,>=2.0 (from aiohttp<4.0,>=3.5->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
     |████████████████████████████████| 143kB 13.2MB/s
Collecting multidict<5.0,>=4.0 (from aiohttp<4.0,>=3.5->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/88/f0/4d4cbd1a3744e3985efa49682352d0703df653ffa76b81f10fed86599a50/multidict-4.5.2-cp37-cp37m-manylinux1_x86_64.whl (309kB)
     |████████████████████████████████| 317kB 12.3MB/s
Collecting aniso8601<=7,>=3 (from graphene<3.0,>=2.1->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/45/a4/b4fcadbdab46c2ec2d2f6f8b4ab3f64fd0040789ac7f065eba82119cd602/aniso8601-7.0.0-py2.py3-none-any.whl (42kB)
     |████████████████████████████████| 51kB 10.9MB/s
Collecting graphql-relay<3,>=2 (from graphene<3.0,>=2.1->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/85/52/0242f2d01a3b925bc200928a2a88925b915b88efcb31c67e966991aa4dee/graphql_relay-2.0.0-py3-none-any.whl
Collecting twisted>=18.7 (from daphne~=2.3->channels<3.0,>=2.2->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/84/af/d15d3686e56c704796b23b67552f3ac78b84652793091a7d7ac8bf2887d7/Twisted-19.7.0-cp37-cp37m-manylinux1_x86_64.whl (3.1MB)
     |████████████████████████████████| 3.1MB 10.9MB/s
Collecting autobahn>=0.18 (from daphne~=2.3->channels<3.0,>=2.2->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/01/f3/42e681a0b1234f1ffdcaf548afe03685ede21ae259de2ea6ad60c83faead/autobahn-19.9.3-py2.py3-none-any.whl (770kB)
     |████████████████████████████████| 778kB 15.3MB/s
Collecting idna>=2.0 (from yarl<2.0,>=1.0->aiohttp<4.0,>=3.5->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
     |████████████████████████████████| 61kB 9.2MB/s
Collecting PyHamcrest>=1.9.0 (from twisted>=18.7->daphne~=2.3->channels<3.0,>=2.2->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/9a/d5/d37fd731b7d0e91afcc84577edeccf4638b4f9b82f5ffe2f8b62e2ddc609/PyHamcrest-1.9.0-py2.py3-none-any.whl (52kB)
     |████████████████████████████████| 61kB 19.8MB/s
Collecting hyperlink>=17.1.1 (from twisted>=18.7->daphne~=2.3->channels<3.0,>=2.2->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/7f/91/e916ca10a2de1cb7101a9b24da546fb90ee14629e23160086cf3361c4fb8/hyperlink-19.0.0-py2.py3-none-any.whl
Collecting constantly>=15.1 (from twisted>=18.7->daphne~=2.3->channels<3.0,>=2.2->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/b9/65/48c1909d0c0aeae6c10213340ce682db01b48ea900a7d9fce7a7910ff318/constantly-15.1.0-py2.py3-none-any.whl
Collecting incremental>=16.10.1 (from twisted>=18.7->daphne~=2.3->channels<3.0,>=2.2->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/f5/1d/c98a587dc06e107115cf4a58b49de20b19222c83d75335a192052af4c4b7/incremental-17.5.0-py2.py3-none-any.whl
Collecting zope.interface>=4.4.2 (from twisted>=18.7->daphne~=2.3->channels<3.0,>=2.2->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/3a/b5/5cbafbe09bbfc242503b0cd9bcf9dee32458b3ca166f6a63cb7b4f465b60/zope.interface-4.6.0-cp37-cp37m-manylinux1_x86_64.whl (167kB)
     |████████████████████████████████| 174kB 15.6MB/s
Collecting Automat>=0.3.0 (from twisted>=18.7->daphne~=2.3->channels<3.0,>=2.2->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/a3/86/14c16bb98a5a3542ed8fed5d74fb064a902de3bdd98d6584b34553353c45/Automat-0.7.0-py2.py3-none-any.whl
Collecting txaio>=18.8.1 (from autobahn>=0.18->daphne~=2.3->channels<3.0,>=2.2->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/e9/6d/e1a6f7835cde86728e5bb1f577be9b2d7d273fdb33c286e70b087d418ded/txaio-18.8.1-py2.py3-none-any.whl
Collecting cryptography>=2.7 (from autobahn>=0.18->daphne~=2.3->channels<3.0,>=2.2->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/97/18/c6557f63a6abde34707196fb2cad1c6dc0dbff25a200d5044922496668a4/cryptography-2.7-cp34-abi3-manylinux1_x86_64.whl (2.3MB)
     |████████████████████████████████| 2.3MB 14.3MB/s
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/site-packages (from PyHamcrest>=1.9.0->twisted>=18.7->daphne~=2.3->channels<3.0,>=2.2->django-channels-graphql-ws) (41.2.0)
Collecting cffi!=1.11.3,>=1.8 (from cryptography>=2.7->autobahn>=0.18->daphne~=2.3->channels<3.0,>=2.2->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/a0/ea/37fe21475c884f88a2ae496cab10e8f84f0cc11137be860af9eb37a3edb9/cffi-1.12.3-cp37-cp37m-manylinux1_x86_64.whl (430kB)
     |████████████████████████████████| 440kB 13.4MB/s
Collecting asn1crypto>=0.21.0 (from cryptography>=2.7->autobahn>=0.18->daphne~=2.3->channels<3.0,>=2.2->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
     |████████████████████████████████| 102kB 17.7MB/s
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=2.7->autobahn>=0.18->daphne~=2.3->channels<3.0,>=2.2->django-channels-graphql-ws)
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
     |████████████████████████████████| 163kB 12.4MB/s
Building wheels for collected packages: promise, yarl, pycparser
  Building wheel for promise (setup.py) ... done
  Created wheel for promise: filename=promise-2.2.1-cp37-none-any.whl size=21291 sha256=3b706b4f393a0a45cdc4fc02e3320971061b08b4bf1268c7ff2ff8a83f6ebe0c
  Stored in directory: /root/.cache/pip/wheels/92/84/9f/75e2235effae0e1c5a5c0626a503e532bbffcb7e79e672b606
  Building wheel for yarl (setup.py) ... done
  Created wheel for yarl: filename=yarl-1.3.0-cp37-cp37m-linux_x86_64.whl size=264936 sha256=695a8e1ad337c46bfe0f1ff8b13e34d5feb66a680cb91cac9c2b9f60d700484b
  Stored in directory: /root/.cache/pip/wheels/e3/f0/13/d7c1c5cd76ef321fb635ce79232ca973cd0c91fabaaa71e1c7
  Building wheel for pycparser (setup.py) ... done
  Created wheel for pycparser: filename=pycparser-2.19-py2.py3-none-any.whl size=111029 sha256=0c313814c3ca44db8dbdbe3f88526a9ef9a015840c8033dba908c218a2fe5d92
  Stored in directory: /root/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built promise yarl pycparser
Installing collected packages: six, promise, rx, graphql-core, asgiref, sqlparse, pytz, django, PyHamcrest, idna, hyperlink, constantly, attrs, incremental, zope.interface, Automat, twisted, txaio, pycparser, cffi, asn1crypto, cryptography, autobahn, daphne, channels, msgpack, async-timeout, multidict, yarl, chardet, aiohttp, aniso8601, graphql-relay, graphene, django-channels-graphql-ws
Successfully installed Automat-0.7.0 PyHamcrest-1.9.0 aiohttp-3.6.0 aniso8601-7.0.0 asgiref-3.2.2 asn1crypto-0.24.0 async-timeout-3.0.1 attrs-19.1.0 autobahn-19.9.3 cffi-1.12.3 channels-2.2.0 chardet-3.0.4 constantly-15.1.0 cryptography-2.7 daphne-2.3.0 django-2.2.5 django-channels-graphql-ws-0.4.2 graphene-2.1.8 graphql-core-2.2.1 graphql-relay-2.0.0 hyperlink-19.0.0 idna-2.8 incremental-17.5.0 msgpack-0.6.1 multidict-4.5.2 promise-2.2.1 pycparser-2.19 pytz-2019.2 rx-1.6.1 six-1.12.0 sqlparse-0.3.0 twisted-19.7.0 txaio-18.8.1 yarl-1.3.0 zope.interface-4.6.0
root@294381deb51f:/#
```

So I support the issue somehow concerns your working environment. Well, I close this issues with the verdict "cannot reproduce". If you have any additional info about the issue please feel free to put it here and reopen the issue.

**Closed by prokher** 2019-09-17 10:44 UTC
