### ISSUE TITLE
Support for Django-GraphQL-Social-Auth

### ISSUE THREAD

**Issue by kingtimm** [datadvance/DjangoChannelsGraphqlWs#26] opened 2019-10-02 03:20 UTC
There are two awesome projects called:

1. https://github.com/flavors/django-graphql-social-auth
2. https://github.com/flavors/django-graphql-jwt

I am trying to use both the django-graphql-social-auth and the django-channels-graphql-ws packages in conjunction with each other. Ultimately, I would like to have a django channels websocket graphql api backend and a JS front-end using social auth.

When using dgql-social-auth with this library, I run into an issue with the request going through the python social auth library here: https://github.com/python-social-auth/social-app-django/blob/c00d23c2b45c3317bd35b15ad1b959338689cef8/social_django/strategy.py#L51

```python
def request_data(self, merge=True):
        if not self.request:
            return {}
        if merge:
            data = self.request.GET.copy()
            data.update(self.request.POST)
        elif self.request.method == 'POST':
            data = self.request.POST
        else:
            data = self.request.GET
        return data
```

I see the following error:

> An error occurred while resolving field Mutation.socialAuth
> Traceback (most recent call last):
>   File "channels_graphql_ws\scope_as_context.py", line 42, in __getattr__
>     return self._scope[name]
> KeyError: 'GET'

I believe this is because of how the websocket request object is formed versus a traditional request object that python social auth would expect.

My code includes adding this mutation to the example in this lib

```python
class Mutation(graphene.ObjectType):
    """Root GraphQL mutation."""

    send_chat_message = SendChatMessage.Field()
    login = Login.Field()
    social_auth = graphql_social_auth.SocialAuthJWT.Field()
```

Using this gql

```graphql
mutation SocialAuth($provider: String!, $accessToken: String!) {
  socialAuth(provider: $provider, accessToken: $accessToken) {
    social {
      uid
    }
    token
  }
}
```

Is there any way to get these two to work together well?

**Comment by carlosalvarez91** [comment] 2020-02-25 09:28
@kingtimm any news on this? I'm having the same issue.

**Comment by prokher** [comment] 2020-07-25 17:38
Dear @kingtimm,

Indeed it looks like one of the libraries you mentioned calls `GET` on the [context](https://github.com/datadvance/DjangoChannelsGraphqlWs#context) instance, typically available as `info.context` in GraphQL resolvers. It is completely unclear for my why `context` became `requiest`. 🤷‍♂️  I could probably take a look deeper if you provide minimal failing example with instructions how to reproduce. Can you please do it?

**Comment by prokher** [comment] 2020-12-05 23:52
Closing this because I cannot reproduce the issue, and I still haven't received an example.

**Closed by prokher** 2020-12-05 23:52 UTC
Labels: question
