### ISSUE TITLE
connection_ack issue...

### ISSUE THREAD

**Issue by sbenou** [datadvance/DjangoChannelsGraphqlWs#57] opened 2021-01-03 21:57 UTC
Hello there,

I am trying to use this library with an Apollo-react app and I am not too sure why I cannot get it to work.

At the moment, I can see mutations, queries and subscriptions in a totally different line on the network tab on google developer tool

when using apollo and nodejs, I can see the result of my subscription on the ws section (which is the payload (result of mutation and query used) on google developer tool network tab ... 

But when trying with your library I can see the "connection_init" message but I am not getting the "connection_ack" message ... I am sure I must be missing something if your library is supposed to work the same
![image](https://user-images.githubusercontent.com/801547/103578630-caf1b600-4ece-11eb-9ffa-4202fe27d7b2.png)

is it supposed to work the same? If it is, then I strongly believe this library should be integrated with graphene as subscriptions are created the same way as mutations ...

Also, when I run the subscription I don't get any result on graphiql, it keeps running on the right hand side of the screen without returning any result (which should probably be the payload (mutation and query used)? 

![image](https://user-images.githubusercontent.com/801547/103579651-9252dc00-4ed0-11eb-8d0f-12d007db9db8.png)

... also as you can see, the user is always returned as None... not sure if it's a graphql middleware issue

![image](https://user-images.githubusercontent.com/801547/103578710-fa082780-4ece-11eb-84a4-e9af85b24bd2.png)

any help will be appreciated

thanks

**Comment by sbenou** [comment] 2021-01-10 03:27
any update guys?

**Comment by prokher** [comment] 2021-02-10 14:43
> Also, when I run the subscription I don't get any result on graphiql, it keeps running on the right hand side of the screen without returning any result (which should probably be the payload (mutation and query used)?

@sbenou Speaking of this, it is OK. Just open another GraphiQL in a new browser tab/window and invoke mutation which triggers the subscription and I'll see the subscription message in the first one.

**Comment by prokher** [comment] 2021-08-08 16:00
@sbenou, I cannot confirm the absence of the `connection_ack` response. I observe it in the example project (located in the `example/`):

![image](https://user-images.githubusercontent.com/399393/128638019-a6912753-ba7b-4aaf-ad91-7a6ee11613ee.png)

Also the client implementation [asserts `connection_ack` is there](https://github.com/datadvance/DjangoChannelsGraphqlWs/blob/master/channels_graphql_ws/client.py#L85).

Take a look at [a function which handles the `connection_init` message](https://github.com/datadvance/DjangoChannelsGraphqlWs/blob/master/channels_graphql_ws/graphql_ws_consumer.py#L463), as far as I see it responds either with `connection_ack` or with the `connection_error` message.

So I am closing this with a verdict "cannot reproduce". If you have something that can help me to reproduce this

**Closed by prokher** 2021-08-08 16:00 UTC
